# Generated by Django 5.2.11 on 2026-03-01 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del cupón')),
                ('descuento', models.PositiveIntegerField(verbose_name='Descuento (%)')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=30, verbose_name='Nombre comercial')),
                ('contacto', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la categoría')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', related_query_name='categoria', to='staff.cupon', verbose_name='Cupón asociado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio de venta')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Coste del producto')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad en stock')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Producto activo?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', related_query_name='producto', to='staff.categoria', verbose_name='Categoría')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', related_query_name='producto', to='staff.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
