# Generated by Django 5.2.11 on 2026-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Código de empresa'),
        ),
    ]
