# Generated by Django 5.2.11 on 2026-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_empresa_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_del_dia',
            field=models.BooleanField(default=False, verbose_name='Producto del día'),
        ),
    ]
